export const bodyTexts = [
    { body: '<p>En las últimas décadas la tecnología no solo se convirtió en una herramienta básica, sino en parte de nuestra vida diaria, al punto de que es casi imposible imaginar cómo sería realizar actividades sin ella.</p>' },
    { body: '<p>Imágenes satelitales, datos de vuelos y movimientos logísticos revelan maniobras masivas centradas en la base estratégica de Diego García, en el océano Índico, y extendidas hasta el Golfo Pérsico</p>' },
    { body: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>' },
    { body: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>' },
    { body: '<p>Un avión de Aerolíneas Argentinas tuvo que dar vueltas durante casi una hora alrededor del aeropuerto internacional de Sauce Viejo, en Santa Fe. La principal hipótesis de la demora apunta a inconvenientes en la comunicación entre el piloto de la aeronave y la torre de control.</p>' },
    { body: '<p> enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute iru</p>' },
    { body: '<p>La Empresa Argentina de Navegación Aérea (EANA), de gestión pública y dependiente de la Secretaría de Transporte de la Nación, es la encargada de los servicios y control de tránsito aéreo. Luego del inconveniente emitieron un comunicado en el que aseguraron haber abierto una investigación sobre lo ocurrido.</p>' },
    { body: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>' },
  ];